# Generated by Django 4.1.3 on 2022-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliersmodels',
            old_name='name',
            new_name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='suppliersmodels',
            name='description',
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='TimeZone',
            field=models.CharField(choices=[('EST', 'Eastern Standard Time'), ('PST', 'Pacific Standard Time'), ('MST', 'Mountain Standard Time'), ('CST', 'Central Standard Time')], default='EST', max_length=50),
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='Type',
            field=models.CharField(choices=[('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer'), ('Wholesaler', 'Wholesaler')], default='Distributor', max_length=12),
        ),
    ]
