# Generated by Django 4.1.3 on 2022-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_name_suppliersmodels_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersmodels',
            name='Address',
            field=models.CharField(default='', max_length=42),
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='City',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='ContactName',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='ContactTitle',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='Email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='Website',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='suppliersmodels',
            name='CompanyName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
