# Generated by Django 4.1.3 on 2022-12-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_suppliersmodels_address_suppliersmodels_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersmodels',
            name='Phone',
            field=models.IntegerField(default='123', max_length=8),
        ),
        migrations.AddField(
            model_name='suppliersmodels',
            name='PostalCode',
            field=models.IntegerField(default='12041', max_length=6),
        ),
    ]
