# Generated by Django 4.1.3 on 2022-12-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_suppliersmodels_phone_suppliersmodels_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersmodels',
            name='Category',
            field=models.CharField(default='Category', max_length=80),
        ),
    ]
