# Generated by Django 4.1.3 on 2022-12-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_suppliersmodels_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuppliersModels',
            new_name='SuppliersModel',
        ),
    ]
